/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_julius_hardt_crypto_shamirs_secret_sharing_ShamirsSecretSharing */

#ifndef _Included_de_julius_hardt_crypto_shamirs_secret_sharing_ShamirsSecretSharing
#define _Included_de_julius_hardt_crypto_shamirs_secret_sharing_ShamirsSecretSharing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_julius_hardt_crypto_shamirs_secret_sharing_ShamirsSecretSharing
 * Method:    share
 * Signature: (II[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_de_julius_1hardt_crypto_shamirs_1secret_1sharing_ShamirsSecretSharing_share
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     de_julius_hardt_crypto_shamirs_secret_sharing_ShamirsSecretSharing
 * Method:    reconstruct
 * Signature: ([[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_julius_1hardt_crypto_shamirs_1secret_1sharing_ShamirsSecretSharing_reconstruct
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
